app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /api/v1

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"