api_v1_get_product:
    path: /{id}
    controller: AppBundle:Product:get
    methods: [GET]
    requirements:
        id: \d+

api_v1_get_all_products:
    path: /
    controller: AppBundle:Product:getAll
    methods: [GET]

api_v1_get_all_products_by_category:
    path: /category/{id}
    controller: AppBundle:Product:getAllByCategory
    methods: [GET]
    requirements:
        id: \d+

api_v1_create_product:
    path: /new
    methods: [POST]
    controller: AppBundle:Product:post

api_v1_update_product:
    path: /{id}/edit
    controller: AppBundle:Product:put
    methods: [PUT]
    requirements:
        id: \d+

api_v1_delete_product:
    path: /{id}
    controller: AppBundle:Product:delete
    methods: [DELETE]
    requirements:
        id: \d+