Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "product-list-vagrant"
    config.vm.define "products_ubuntu_vagrant"
    config.vm.network "private_network", ip: "192.168.35.10"
    config.vm.hostname = "products.dev"
    config.hostsupdater.aliases = ["products.dev", "www.products.dev"]

    config.vm.synced_folder "../", "/sync"
    config.vm.synced_folder "../", "/var/www/products", owner: "www-data", group: "www-data"

    config.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
         vb.cpus = 2
    end

    config.vm.provision "shell", path: "vagrant_files/ansible.sh"
end