---
#- name: Stop Web servers
#  service:
#    name: "{{item}}"
#    state: stopped
#  with_items:
#      - apache2
#      - php5-fpm
#      - nginx
#  when: "'testqa' in group_names"
 
- name: Install common software packages
  apt:
    package: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
    state: present
  with_items:
    - git

- name: Create logs directory
  file:
    path: "/var/log/products"
    state: directory
    owner: root
    group: root