AppBundle\Entity\Color:
    exclusion_policy: ALL
    properties:
        id:
            read_only: true
            groups: [default, update]
        value:
            type: string
            groups: [default, create, update]
        type:
            type: string
            groups: [default, create, update]