AppBundle\Entity\IsActive:
    exclusion_policy: ALL
    properties:
        id:
            read_only: true
            groups: [default, update]
        value:
            type: bool
            groups: [default, create, update]

    virtual_properties:
        getAttributeName:
            serialized_name: attribute
            type: string
            accessor:
                getter: getAttributeName
            read_only: true
            groups: [default]