AppBundle\Entity\GroupType:
     exclusion_policy: ALL
     properties:
        id:
            type: integer
            groups: [default, create, update]
        name:
            type: string
            groups: [default, create, update]