AppBundle\Entity\Product:
    exclusion_policy: ALL
    properties:
        id:
            read_only: true
            groups: [default, create, update]
        name:
            type: string
            groups: [default, create, update]
        price:
            type: float
            groups: [default, create, update]
        categories:
            type: ArrayCollection<AppBundle\Entity\Category>
            groups: [default, create, update]
        attributes:
            type: ArrayCollection<AppBundle\Entity\ProductAttributes>
            groups: [default, create, update]