AppBundle\Entity\Color:
    exclusion_policy: ALL
    properties:
        id:
            read_only: true
            groups: [default, update]
        value:
            type: string
            groups: [default, create, update]
    virtual_properties:
        getAttributeName:
            serialized_name: attribute
            type: string
            accessor:
                getter: getAttributeName
            read_only: true
            groups: [default]