AppBundle\Entity\IsActive:
    exclusion_policy: ALL
    properties:
        id:
            read_only: true
            groups: [default, update]
        value:
            type: bool
            groups: [default, create, update]