AppBundle\Entity\AccessToken:
    type: entity
    table: oauth2_access_token
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: Client
            joinColumns:
