AppBundle\Entity\Category:
    type: entity
    table: categories
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: false
            length: 64
            fixed: false