AppBundle\Entity\Category:
    type: entity
    table: categories
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: false
            length: 64
            fixed: false
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        lvl:
            type: integer
            gedmo:
                - treeLevel
    manyToOne:
        root:
            targetEntity: AppBundle\Entity\Category
            joinColumn:
                name: tree_root
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
              - treeRoot
        parent:
            targetEntity: AppBundle\Entity\Category
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: AppBundle\Entity\Category
            mappedBy: parent
            orderBy:
                lft: ASC
    manyToMany:
        products:
            targetEntity: AppBundle\Entity\Product
            mappedBy: categories