AppBundle\Entity\IsActive:
    type: entity
    table: product_is_active
    extends: AppBundle\Entity\ProductAttributes
    fields:
        value:
            type: boolean
            nullable: false