AppBundle\Entity\ProductAttributes:
    type: entity
    inheritanceType: JOINED
    discriminatorColumn:
        name: dtype
        type: string
        length: 255
    discriminatorMap:
        size: AppBundle\Entity\Size
        color: AppBundle\Entity\Color
        is_active: AppBundle\Entity\IsActive
        group: AppBundle\Entity\Group
    table: product_attributes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        product:
            targetEntity: AppBundle\Entity\Product
            inversedBy: attributes
