AppBundle\Entity\ProductAttributes\Color:
    type: entity
    table: product_color
    extends: AppBundle\Entity\ProductAttributes
    fields:
        value:
            type: string
            nullable: false
        type:
            type: string
            nullable: false