AppBundle\Entity\Product:
    type: entity
    table: products
    repositoryClass: AppBundle\Repository\ProductRepository
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
        price:
            type: float
            nullable: false
    manyToMany:
        categories:
            targetEntity: AppBundle\Entity\Category
            inversedBy: products
    oneToMany:
        attributes:
            targetEntity: AppBundle\Entity\ProductAttributes
            mappedBy: product
            cascade: ["persist", "merge", "detach"]