AppBundle\Entity\RefreshToken:
    type: entity
    table: oauth2_refresh_token
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: AppBundle\Entity\Client
        user:
            targetEntity: AppBundle\Entity\User
