AppBundle\Entity\Category:
    properties:
        title:
            - Type:
                type: string
                groups: [create, update]
            - NotBlank:
                groups: [create, update]
        parent:
            - Type:
                type: AppBundle\Entity\Category
                groups: [create, update]
            - AppBundle\Validator\Constraints\CategoryExisting:
                groups: [create, update]