AppBundle\Entity\Color:
    properties:
        value:
            - Type:
                type: string
                groups: [create, update]
            - NotBlank:
                groups: [create, update]
            - NotNull:
                groups: [create, update]