AppBundle\Entity\Product:
    properties:
        name:
            - Type:
                type: string
                groups: [create, update]
            - NotBlank:
                groups: [create, update]
        price:
            - Type:
                type: float
                groups: [create, update]
            - NotBlank:
                groups: [create, update]